{
	"document": {
		"aggregate_severity": {
			"namespace": "https://www.suse.com/support/security/rating/",
			"text": "moderate"
		},
		"category": "csaf_vex",
		"csaf_version": "2.0",
		"distribution": {
			"text": "Copyright 2023 SUSE LLC. All rights reserved.",
			"tlp": {
				"label": "WHITE",
				"url": "https://www.first.org/tlp/"
			}
		},
		"lang": "en",
		"notes": [
			{
				"category": "summary",
				"text": "SUSE CVE-2014-3730",
				"title": "Title"
			},
			{
				"category": "description",
				"text": "The django.util.http.is_safe_url function in Django 1.4 before 1.4.13, 1.5 before 1.5.8, 1.6 before 1.6.5, and 1.7 before 1.7b4 does not properly validate URLs, which allows remote attackers to conduct open redirect attacks via a malformed URL, as demonstrated by \"http:\\\\\\djangoproject.com.\"",
				"title": "Description of the CVE"
			},
			{
				"category": "legal_disclaimer",
				"text": "CSAF 2.0 data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
				"title": "Terms of use"
			}
		],
		"publisher": {
			"category": "vendor",
			"contact_details": "https://www.suse.com/support/security/contact/",
			"name": "SUSE Product Security Team",
			"namespace": "https://www.suse.com/"
		},
		"references": [
			{
				"category": "external",
				"summary": "CVE-2014-3730",
				"url": "https://www.suse.com/security/cve/CVE-2014-3730"
			},
			{
				"category": "external",
				"summary": "SUSE Security Ratings",
				"url": "https://www.suse.com/support/security/rating/"
			},
			{
				"category": "external",
				"summary": "SUSE Bug 878641 for CVE-2014-3730",
				"url": "https://bugzilla.suse.com/878641"
			},
			{
				"category": "external",
				"summary": "Advisory link for SUSE-SU-2014:0851-1",
				"url": "https://lists.suse.com/pipermail/sle-security-updates/2014-June/000894.html"
			},
			{
				"category": "external",
				"summary": "Advisory link for openSUSE-SU-2014:1132-1",
				"url": "https://lists.opensuse.org/opensuse-updates/2014-09/msg00023.html"
			}
		],
		"title": "SUSE CVE CVE-2014-3730",
		"tracking": {
			"current_release_date": "2023-02-15T05:28:16Z",
			"generator": {
				"date": "2023-02-15T05:28:16Z",
				"engine": {
					"name": "cve-database.git:bin/generate-csaf-vex.pl",
					"version": "1"
				}
			},
			"id": "CVE-2014-3730",
			"initial_release_date": "2023-02-15T05:28:16Z",
			"revision_history": [
				{
					"date": "2023-02-15T05:28:16Z",
					"number": "2",
					"summary": "Current version"
				}
			],
			"status": "interim",
			"version": "2"
		}
	},
	"product_tree": {
		"branches": [
			{
				"branches": [
					{
						"branches": [
							{
								"category": "product_name",
								"name": "SUSE OpenStack Cloud 3.0",
								"product": {
									"name": "SUSE OpenStack Cloud 3.0",
									"product_id": "SUSE OpenStack Cloud 3.0"
								}
							},
							{
								"category": "product_version",
								"name": "python-django-1.5.8-0.7.1",
								"product": {
									"name": "python-django-1.5.8-0.7.1",
									"product_id": "python-django-1.5.8-0.7.1",
									"product_identification_helper": {
										"cpe": "cpe:2.3:a:djangoproject:django:1.5.8:*:*:*:*:*:*:*"
									}
								}
							}
						],
						"category": "product_family",
						"name": "SUSE Linux Enterprise"
					}
				],
				"category": "vendor",
				"name": "SUSE"
			}
		],
		"relationships": [
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-django-1.5.8-0.7.1 as component of SUSE OpenStack Cloud 3.0",
					"product_id": "SUSE OpenStack Cloud 3.0:python-django-1.5.8-0.7.1"
				},
				"product_reference": "python-django-1.5.8-0.7.1",
				"relates_to_product_reference": "SUSE OpenStack Cloud 3.0"
			}
		]
	},
	"vulnerabilities": [
		{
			"cve": "CVE-2014-3730",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2014-3730"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "The django.util.http.is_safe_url function in Django 1.4 before 1.4.13, 1.5 before 1.5.8, 1.6 before 1.6.5, and 1.7 before 1.7b4 does not properly validate URLs, which allows remote attackers to conduct open redirect attacks via a malformed URL, as demonstrated by \"http:\\\\\\djangoproject.com.\"",
					"title": "Vulnerability description"
				}
			],
			"product_status": {
				"fixed": [
					"SUSE OpenStack Cloud 3.0:python-django-1.5.8-0.7.1"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2014-3730",
					"url": "https://www.suse.com/security/cve/CVE-2014-3730"
				},
				{
					"category": "external",
					"summary": "SUSE Security Ratings",
					"url": "https://www.suse.com/support/security/rating/"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 878641 for CVE-2014-3730",
					"url": "https://bugzilla.suse.com/878641"
				},
				{
					"category": "external",
					"summary": "Advisory link for SUSE-SU-2014:0851-1",
					"url": "https://lists.suse.com/pipermail/sle-security-updates/2014-June/000894.html"
				},
				{
					"category": "external",
					"summary": "Advisory link for openSUSE-SU-2014:1132-1",
					"url": "https://lists.opensuse.org/opensuse-updates/2014-09/msg00023.html"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"SUSE OpenStack Cloud 3.0:python-django-1.5.8-0.7.1"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2014-05-16T18:16:34Z",
					"details": "moderate"
				}
			],
			"title": "CVE-2014-3730"
		}
	]
}
