{
	"document": {
		"aggregate_severity": {
			"namespace": "https://www.suse.com/support/security/rating/",
			"text": "moderate"
		},
		"category": "csaf_vex",
		"csaf_version": "2.0",
		"distribution": {
			"text": "Copyright 2024 SUSE LLC. All rights reserved.",
			"tlp": {
				"label": "WHITE",
				"url": "https://www.first.org/tlp/"
			}
		},
		"lang": "en",
		"notes": [
			{
				"category": "summary",
				"text": "SUSE CVE-2014-0481",
				"title": "Title"
			},
			{
				"category": "description",
				"text": "The default configuration for the file upload handling system in Django before 1.4.14, 1.5.x before 1.5.9, 1.6.x before 1.6.6, and 1.7 before release candidate 3 uses a sequential file name generation process when a file with a conflicting name is uploaded, which allows remote attackers to cause a denial of service (CPU consumption) by unloading a multiple files with the same name.",
				"title": "Description of the CVE"
			},
			{
				"category": "legal_disclaimer",
				"text": "CSAF 2.0 data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
				"title": "Terms of use"
			}
		],
		"publisher": {
			"category": "vendor",
			"contact_details": "https://www.suse.com/support/security/contact/",
			"name": "SUSE Product Security Team",
			"namespace": "https://www.suse.com/"
		},
		"references": [
			{
				"category": "external",
				"summary": "CVE-2014-0481",
				"url": "https://www.suse.com/security/cve/CVE-2014-0481"
			},
			{
				"category": "external",
				"summary": "SUSE Security Ratings",
				"url": "https://www.suse.com/support/security/rating/"
			},
			{
				"category": "external",
				"summary": "SUSE Bug 893088 for CVE-2014-0481",
				"url": "https://bugzilla.suse.com/893088"
			},
			{
				"category": "external",
				"summary": "SUSE Bug 919763 for CVE-2014-0481",
				"url": "https://bugzilla.suse.com/919763"
			},
			{
				"category": "external",
				"summary": "Advisory link for SUSE-SU-2014:1153-1",
				"url": "https://lists.suse.com/pipermail/sle-security-updates/2014-September/001009.html"
			}
		],
		"title": "SUSE CVE CVE-2014-0481",
		"tracking": {
			"current_release_date": "2023-12-08T04:52:48Z",
			"generator": {
				"date": "2023-02-15T05:32:01Z",
				"engine": {
					"name": "cve-database.git:bin/generate-csaf-vex.pl",
					"version": "1"
				}
			},
			"id": "CVE-2014-0481",
			"initial_release_date": "2023-02-15T05:32:01Z",
			"revision_history": [
				{
					"date": "2023-02-15T05:32:01Z",
					"number": "2",
					"summary": "Current version"
				},
				{
					"date": "2023-12-08T04:52:48Z",
					"number": "3",
					"summary": "Current version"
				}
			],
			"status": "interim",
			"version": "3"
		}
	},
	"product_tree": {
		"branches": [
			{
				"branches": [
					{
						"branches": [
							{
								"category": "product_name",
								"name": "SUSE OpenStack Cloud 3.0",
								"product": {
									"name": "SUSE OpenStack Cloud 3.0",
									"product_id": "SUSE OpenStack Cloud 3.0"
								}
							},
							{
								"category": "product_name",
								"name": "SUSE OpenStack Cloud 4",
								"product": {
									"name": "SUSE OpenStack Cloud 4",
									"product_id": "SUSE OpenStack Cloud 4",
									"product_identification_helper": {
										"cpe": "cpe:/o:suse:cloud:4"
									}
								}
							},
							{
								"category": "product_version",
								"name": "python-django-1.5.10-0.11.1",
								"product": {
									"name": "python-django-1.5.10-0.11.1",
									"product_id": "python-django-1.5.10-0.11.1",
									"product_identification_helper": {
										"cpe": "cpe:2.3:a:djangoproject:django:1.5.10:*:*:*:*:*:*:*"
									}
								}
							},
							{
								"category": "product_version",
								"name": "python-django-1.5.10-0.8.1",
								"product": {
									"name": "python-django-1.5.10-0.8.1",
									"product_id": "python-django-1.5.10-0.8.1",
									"product_identification_helper": {
										"cpe": "cpe:2.3:a:djangoproject:django:1.5.10:*:*:*:*:*:*:*"
									}
								}
							}
						],
						"category": "product_family",
						"name": "SUSE Linux Enterprise"
					}
				],
				"category": "vendor",
				"name": "SUSE"
			}
		],
		"relationships": [
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-django-1.5.10-0.8.1 as component of SUSE OpenStack Cloud 3.0",
					"product_id": "SUSE OpenStack Cloud 3.0:python-django-1.5.10-0.8.1"
				},
				"product_reference": "python-django-1.5.10-0.8.1",
				"relates_to_product_reference": "SUSE OpenStack Cloud 3.0"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-django-1.5.10-0.11.1 as component of SUSE OpenStack Cloud 4",
					"product_id": "SUSE OpenStack Cloud 4:python-django-1.5.10-0.11.1"
				},
				"product_reference": "python-django-1.5.10-0.11.1",
				"relates_to_product_reference": "SUSE OpenStack Cloud 4"
			}
		]
	},
	"vulnerabilities": [
		{
			"cve": "CVE-2014-0481",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2014-0481"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "The default configuration for the file upload handling system in Django before 1.4.14, 1.5.x before 1.5.9, 1.6.x before 1.6.6, and 1.7 before release candidate 3 uses a sequential file name generation process when a file with a conflicting name is uploaded, which allows remote attackers to cause a denial of service (CPU consumption) by unloading a multiple files with the same name.",
					"title": "CVE description"
				}
			],
			"product_status": {
				"fixed": [
					"SUSE OpenStack Cloud 3.0:python-django-1.5.10-0.8.1",
					"SUSE OpenStack Cloud 4:python-django-1.5.10-0.11.1"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2014-0481",
					"url": "https://www.suse.com/security/cve/CVE-2014-0481"
				},
				{
					"category": "external",
					"summary": "SUSE Security Ratings",
					"url": "https://www.suse.com/support/security/rating/"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 893088 for CVE-2014-0481",
					"url": "https://bugzilla.suse.com/893088"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 919763 for CVE-2014-0481",
					"url": "https://bugzilla.suse.com/919763"
				},
				{
					"category": "external",
					"summary": "Advisory link for SUSE-SU-2014:1153-1",
					"url": "https://lists.suse.com/pipermail/sle-security-updates/2014-September/001009.html"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"SUSE OpenStack Cloud 3.0:python-django-1.5.10-0.8.1",
						"SUSE OpenStack Cloud 4:python-django-1.5.10-0.11.1"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2014-08-21T22:16:12Z",
					"details": "moderate"
				}
			],
			"title": "CVE-2014-0481"
		}
	]
}
