{
	"document": {
		"aggregate_severity": {
			"namespace": "https://www.suse.com/support/security/rating/",
			"text": "moderate"
		},
		"category": "csaf_vex",
		"csaf_version": "2.0",
		"distribution": {
			"text": "Copyright 2025 SUSE LLC. All rights reserved.",
			"tlp": {
				"label": "WHITE",
				"url": "https://www.first.org/tlp/"
			}
		},
		"lang": "en",
		"notes": [
			{
				"category": "summary",
				"text": "SUSE CVE-2024-32879",
				"title": "Title"
			},
			{
				"category": "description",
				"text": "Python Social Auth is a social authentication/registration mechanism. Prior to version 5.4.1, due to default case-insensitive collation in MySQL or MariaDB databases, third-party authentication user IDs are not case-sensitive and could cause different IDs to match. This issue has been addressed by a fix released in version 5.4.1. An immediate workaround would be to change collation of the affected field.",
				"title": "Description of the CVE"
			},
			{
				"category": "legal_disclaimer",
				"text": "CSAF 2.0 data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
				"title": "Terms of use"
			}
		],
		"publisher": {
			"category": "vendor",
			"contact_details": "https://www.suse.com/support/security/contact/",
			"name": "SUSE Product Security Team",
			"namespace": "https://www.suse.com/"
		},
		"references": [
			{
				"category": "external",
				"summary": "CVE-2024-32879",
				"url": "https://www.suse.com/security/cve/CVE-2024-32879"
			},
			{
				"category": "external",
				"summary": "SUSE Security Ratings",
				"url": "https://www.suse.com/support/security/rating/"
			},
			{
				"category": "external",
				"summary": "SUSE Bug 1223373 for CVE-2024-32879",
				"url": "https://bugzilla.suse.com/1223373"
			}
		],
		"title": "SUSE CVE CVE-2024-32879",
		"tracking": {
			"current_release_date": "2025-01-01T01:12:11Z",
			"generator": {
				"date": "2024-04-25T23:11:27Z",
				"engine": {
					"name": "cve-database.git:bin/generate-csaf-vex.pl",
					"version": "1"
				}
			},
			"id": "CVE-2024-32879",
			"initial_release_date": "2024-04-25T23:11:27Z",
			"revision_history": [
				{
					"date": "2024-04-25T23:11:27Z",
					"number": "2",
					"summary": "Current version"
				},
				{
					"date": "2024-06-11T02:08:56Z",
					"number": "3",
					"summary": "Current version"
				},
				{
					"date": "2025-01-01T01:12:11Z",
					"number": "4",
					"summary": "Current version"
				}
			],
			"status": "interim",
			"version": "4"
		}
	},
	"product_tree": {
		"branches": [
			{
				"branches": [
					{
						"branches": [
							{
								"category": "product_name",
								"name": "openSUSE Tumbleweed",
								"product": {
									"name": "openSUSE Tumbleweed",
									"product_id": "openSUSE Tumbleweed",
									"product_identification_helper": {
										"cpe": "cpe:/o:opensuse:tumbleweed"
									}
								}
							},
							{
								"category": "product_version",
								"name": "python310-social-auth-app-django-5.4.1-1.1",
								"product": {
									"name": "python310-social-auth-app-django-5.4.1-1.1",
									"product_id": "python310-social-auth-app-django-5.4.1-1.1"
								}
							},
							{
								"category": "product_version",
								"name": "python311-social-auth-app-django-5.4.1-1.1",
								"product": {
									"name": "python311-social-auth-app-django-5.4.1-1.1",
									"product_id": "python311-social-auth-app-django-5.4.1-1.1"
								}
							},
							{
								"category": "product_version",
								"name": "python312-social-auth-app-django-5.4.1-1.1",
								"product": {
									"name": "python312-social-auth-app-django-5.4.1-1.1",
									"product_id": "python312-social-auth-app-django-5.4.1-1.1"
								}
							}
						],
						"category": "product_family",
						"name": "SUSE Linux Enterprise"
					}
				],
				"category": "vendor",
				"name": "SUSE"
			}
		],
		"relationships": [
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python310-social-auth-app-django-5.4.1-1.1 as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python310-social-auth-app-django-5.4.1-1.1"
				},
				"product_reference": "python310-social-auth-app-django-5.4.1-1.1",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python311-social-auth-app-django-5.4.1-1.1 as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python311-social-auth-app-django-5.4.1-1.1"
				},
				"product_reference": "python311-social-auth-app-django-5.4.1-1.1",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python312-social-auth-app-django-5.4.1-1.1 as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python312-social-auth-app-django-5.4.1-1.1"
				},
				"product_reference": "python312-social-auth-app-django-5.4.1-1.1",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			}
		]
	},
	"vulnerabilities": [
		{
			"cve": "CVE-2024-32879",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2024-32879"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "Python Social Auth is a social authentication/registration mechanism. Prior to version 5.4.1, due to default case-insensitive collation in MySQL or MariaDB databases, third-party authentication user IDs are not case-sensitive and could cause different IDs to match. This issue has been addressed by a fix released in version 5.4.1. An immediate workaround would be to change collation of the affected field.",
					"title": "CVE description"
				}
			],
			"product_status": {
				"recommended": [
					"openSUSE Tumbleweed:python310-social-auth-app-django-5.4.1-1.1",
					"openSUSE Tumbleweed:python311-social-auth-app-django-5.4.1-1.1",
					"openSUSE Tumbleweed:python312-social-auth-app-django-5.4.1-1.1"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2024-32879",
					"url": "https://www.suse.com/security/cve/CVE-2024-32879"
				},
				{
					"category": "external",
					"summary": "SUSE Security Ratings",
					"url": "https://www.suse.com/support/security/rating/"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1223373 for CVE-2024-32879",
					"url": "https://bugzilla.suse.com/1223373"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"openSUSE Tumbleweed:python310-social-auth-app-django-5.4.1-1.1",
						"openSUSE Tumbleweed:python311-social-auth-app-django-5.4.1-1.1",
						"openSUSE Tumbleweed:python312-social-auth-app-django-5.4.1-1.1"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2024-04-24T22:00:04Z",
					"details": "moderate"
				}
			],
			"title": "CVE-2024-32879"
		}
	]
}
